// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFtH6YS5Q8N0L0k0hyCqj0VgnGjPEq_Ek',
    appId: '1:193699807419:web:6354bf728dd2a5c3d6e99e',
    messagingSenderId: '193699807419',
    projectId: 'mobisor-1606',
    authDomain: 'mobisor-1606.firebaseapp.com',
    storageBucket: 'mobisor-1606.appspot.com',
    measurementId: 'G-05PVY05S83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JtIvXrAv-DtJojoPmm6K904jLlfKk9I',
    appId: '1:193699807419:android:656a4d2b59647f7bd6e99e',
    messagingSenderId: '193699807419',
    projectId: 'mobisor-1606',
    storageBucket: 'mobisor-1606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCih4tabz0Wb19cuwRwkeKjrN94XnckWnw',
    appId: '1:193699807419:ios:c29b70a1d9789751d6e99e',
    messagingSenderId: '193699807419',
    projectId: 'mobisor-1606',
    storageBucket: 'mobisor-1606.appspot.com',
    iosClientId: '193699807419-kb14b38jai13cj0fjmelol8jgsvfv78r.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
